// Generated by scripts/build-cloudbase-sportradar.mjs; edit the TypeScript source.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.aiRequestGuard = void 0;
exports.buildAiRequestKey = buildAiRequestKey;
exports.createAiRequestGuard = createAiRequestGuard;
const node_crypto_1 = require("node:crypto");
function buildAiRequestKey(apiKey, request) {
    return (0, node_crypto_1.createHash)("sha256").update(JSON.stringify(["ai-guard-v1", apiKey, request])).digest("hex");
}
function positiveLimit(value, fallback, max) {
    const parsed = Number(value);
    return Number.isInteger(parsed) && parsed > 0 ? Math.min(parsed, max) : fallback;
}
// These are per-process limits. A multi-instance deployment still needs a shared quota store.
function createAiRequestGuard(env = process.env, now = Date.now) {
    const maxConcurrent = positiveLimit(env.AI_MAX_CONCURRENT, 2, 8);
    const hourlyCap = positiveLimit(env.AI_MAX_HOURLY_CALLS, 60, 1000);
    const dailyCap = positiveLimit(env.AI_MAX_DAILY_CALLS, 200, 5000);
    const pending = new Map();
    const cache = new Map();
    let active = 0, hour = -1, day = -1, hourlyCalls = 0, dailyCalls = 0;
    async function run(key, work, cacheTtlMs = 0) {
        const time = now();
        const cached = cache.get(key);
        if (cached && cached.expiresAt > time)
            return cached.value;
        if (cached)
            cache.delete(key);
        if (pending.has(key))
            return pending.get(key);
        if (Math.floor(time / 3_600_000) !== hour) {
            hour = Math.floor(time / 3_600_000);
            hourlyCalls = 0;
        }
        if (Math.floor(time / 86_400_000) !== day) {
            day = Math.floor(time / 86_400_000);
            dailyCalls = 0;
        }
        if (hourlyCalls >= hourlyCap || dailyCalls >= dailyCap)
            return { ok: false, message: "AI_CALL_LIMIT：当前时段调用次数已达到保护上限。" };
        if (active >= maxConcurrent)
            return { ok: false, message: "AI_BUSY：当前 AI 请求较多，请稍后再试。" };
        active++;
        hourlyCalls++;
        dailyCalls++;
        const task = Promise.resolve().then(work).then(value => {
            const ttl = value.ok ? Math.max(0, Math.min(Number.isFinite(cacheTtlMs) ? cacheTtlMs : 0, 7 * 86_400_000)) : 30_000;
            if (ttl > 0) {
                if (!cache.has(key) && cache.size >= 128)
                    cache.delete(cache.keys().next().value);
                cache.set(key, { expiresAt: now() + ttl, value });
            }
            return value;
        }).finally(() => { active--; pending.delete(key); });
        pending.set(key, task);
        return task;
    }
    return { run };
}
exports.aiRequestGuard = createAiRequestGuard();
