// Generated by scripts/build-cloudbase-sportradar.mjs; edit the TypeScript source.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildCreativeBrief = buildCreativeBrief;
exports.hasDistinctTopicAngles = hasDistinctTopicAngles;
exports.isCompleteHotTopicDraft = isCompleteHotTopicDraft;
const platformGuides = {
    B站: "B站：给观众一个具体、值得展开的问题；标题有判断或反差，开场直接亮出抓手。讲解允许自嘲、游戏或动漫类比，但不要强行套角色。弹幕互动围绕一个具体选择，不写‘记得三连’凑字。",
    微博: "微博：像一个真看了内容的人在说话，第一句就是立场或细节，随后给事实支撑和一个可回应的问题。话题标签只用相关人物/事件，不编热搜；不写视频制作方案。",
    小红书: "小红书：封面给具体收获或认知反差，每页一个重点；解释新手可能误解的地方，让读者知道收藏后能用来做什么。不套‘家人们谁懂啊’、‘姐妹们冲’。",
    抖音: "抖音：前三秒给可见的动作、对比或具体疑问；按‘画面｜口播’写镜头，句子短，口播能一口气读完。素材没提供时只写拟制作画面，不假装已有录像。",
    公众号: "公众号：先亮出核心判断，再给事实、解释和反例，段落之间有推进。允许克制而鲜明的观点，不写工作汇报式‘传播价值分析’。"
};
const toneGuides = {
    客观资讯: "客观资讯：抓手来自信息本身，不强加段子、悬念和煽情；已知事实优先。",
    专业复盘: "专业复盘：从一个具体疑问推进到证据和解释；用人话解释术语，因果没有依据就只谈对照。",
    球迷讨论: "球迷讨论：给两个都有理由的选择，让观众说出依据，不以辱骂和站队代替观点。",
    轻松整活: "轻松整活：可以用打工、考试、游戏任务、角色关系等生活化类比；类比不是事实，必须能回扣到当前材料。宁可一个贴切比喻，不硬塞流行梗。",
    人物故事: "人物故事：从人物已确认的动作或处境切入，不替人物编造心理活动、发言和个人经历。",
    数据解读: "数据解读：数字服务于一个问题，明确口径；没有技术统计就换角度，不拿热度分数解释比赛。",
    稳妥表达: "稳妥表达：鲜明观点与事实分开写，不机械堆免责声明，也不把无根据的猜测变成事实。"
};
const kindGuides = {
    选题: "选题：正好5项，每项只含角度标题、怎么做、说明，每项合计80至120字。标题12至24字，至少3条不用问号；不要把一整组统计抄进标题，不出现证据编号和内部工作术语。怎么做：先用引号给出可直接读的开场原句，再简述两个推进动作，不用‘开头直接抛一个疑问’代替台词。说明：只用一句话给事实抓手与观众收获，不重复免责声明。五个统计指标拆成五道数据问答不算不同创意。五项使用不同机制：反差视觉、观众代入/选择挑战、贴切类比或二创、知识误区澄清、结构悬念或评论共创；围绕所选主题，不硬套缺少依据的内容。不要求新事实才能创新，同一事实可以有不同表达，但不能全是罗列数据后问‘为什么’。不要追加整段风险提醒，核验边界必要时只在相应说明里简短指出。",
    标题: "标题：给出5个不同标题，不是替换同义词；分别尝试具体反差、动作瞬间、立场、观众问题、轻松类比，缺乏事实支撑的机制不用。每个标题单独一行，不附正文。",
    短文案: "短文案：只给一版能直接发布的文字，开头一句抓住具体细节或观点，中段给支撑，最后留一个明确讨论口；不要写‘开头钩子：’等编辑标签。",
    视频脚本: "视频脚本：开场钩子、两到三个推进段、结尾互动；每段包含拟制作画面和可直接朗读的口播，不只写‘展示画面、分析数据’。",
    评论区互动: "评论区互动：围绕具体选择、判断或经验提问，不用‘大家怎么看’‘谁更强’；不同问题不能只是换主语。",
    图文卡片: "图文卡片：封面加3至5页；每页有具体标题和正文，视觉建议围绕同一信息，不写空白制作指令。"
};
function buildCreativeBrief(input) {
    return [
        "创作标准：面向观众写作品，不向运营人员汇报工作。网感来自具体处境、认知反差和说话节奏，不是堆梗、感叹号和形容词。",
        "在内部先找当前素材的独特之处：谁做了什么、哪里出乎预期、观众会卡在哪个问题。构思不同候选，再删去换一个热点后仍能原封不动使用的角度；不输出筛选过程。",
        "开头钩子必须兑现：提出的问题要在内容中回答，不能凭空承诺逆转、绝杀、秘密或内幕。标题不要‘这场球别只看比分’‘三个瞬间看懂’‘为什么值得复盘’等无具体信息的万能句。",
        "表达可以鲜明、幽默；事实与观点分开。标题里的疑问句不能暗示未经证实的事实；不能把标题中的说法直接当官方结论。类比不是事实，不编心理活动、采访、历史纪录和比赛节点。",
        "热度、排名、价值分是运营信号，不是比赛证据，也不是观众必须阅读的正文；除非用户明确在制作热榜分析，否则不要复述这些内部指标。",
        "不要凭空比较传播效果，材料没有对照就不能说‘比进球更出圈’‘一句话盖过一场比赛’。专业判断也要有边界：单项角球、犯规和黄牌不能证明具体战术、裁判尺度或门将表现；可提出讨论，不当成已确认原因。",
        input.chain === "hot"
            ? "热点链路：从标题与摘要中提取具体事件或已有观点，不把‘话题上榜’当整篇内容。仅有标题时，可设计围绕标题讨论的观点问答、规则科普或二创方案，不能补造事发过程和结果。"
            : "赛事链路：选题围绕当前比赛的已确认事件和数据；baselineTopics、analysis 只作角度参考，不是新增事实来源。数据不足就换成已知赛果、规则或观点角度，不强行凑战术结论。",
        input.platform ? platformGuides[input.platform] ?? "按所选平台的阅读节奏组织。" : "六个赛事选题兼顾深度、轻量、人物和互动，但不为凑类型硬造事实。",
        input.tone ? toneGuides[input.tone] ?? "保持所选风格，不把专业复盘强行写成搞笑内容。" : "保持表达自然，不强迫每个角度都整活。",
        input.contentType ? kindGuides[input.contentType] ?? "按指定产物结构输出，不混入其他类型。" : "每个选题写明确的核心问题，coreAngle 给开头钩子和推进方式，sampleTitles 给不同的观众标题，reason 写事实抓手。",
        input.length === "短"
            ? "字数要求不能截断必要结构：选题/标题必须保留5项，选题每项约60至100字；其他短内容删铺垫，不删事实支撑。"
            : "保留必要结构，短段落，每段只讲一个重点；不重复同一事实凑长度。",
        "表达示例仅解释方法，不能挪用为当前事实：若证据确实显示低控球方赢球，可从‘球权占有，不等于机会兑现’切入；若标题仅讨论球员首发，可把‘名气还是适配’做成阵容选择题，不宣称他已经被弃用。",
        buildMatchFactChecks(input.matchContext),
        "输出前自检：标题是否具体、开头是否兑现、角度是否不同、做法是否可执行、事实是否来自当前材料。不合格的候选在本次回答内重写，不增加额外模型调用。最终直接返回作品，不复述检查清单和‘当前材料缺失’的长篇说明。"
    ].filter(Boolean).join("\n");
}
function buildMatchFactChecks(context) {
    if (!context?.matchInfo)
        return "";
    const { teamA, teamB, score } = context.matchInfo;
    const goals = String(score).match(/^(\d+)\s*[-:]\s*(\d+)/);
    const checks = [`事实方向校验（仅用于内部自检）：${teamA}在比分左侧，${teamB}在右侧，比分${score}；不要交换主语。`];
    if (context.verifiedStats === true) {
        const metrics = [["射门", "shots"], ["射正", "shotsOnTarget"], ["控球率", "possession"], ["角球", "corners"], ["犯规", "fouls"], ["黄牌", "yellowCards"]];
        for (const [label, key] of metrics) {
            const a = context.stats?.teamA?.[key], b = context.stats?.teamB?.[key];
            if (typeof a !== "number" || typeof b !== "number" || !Number.isFinite(a) || !Number.isFinite(b))
                continue;
            checks.push(`${teamA}${label}${a}${a === b ? "等于" : a > b ? "多于" : "少于"}${teamB}${label}${b}。`);
        }
        const a = context.stats?.teamA?.shotsOnTarget, b = context.stats?.teamB?.shotsOnTarget;
        if (goals && typeof a === "number" && typeof b === "number" && a > 0 && b > 0 && Number(goals[1]) * b === Number(goals[2]) * a) {
            checks.push("两队的进球数/射正次数比值相同，不能以此制造‘射正转化效率差’；这个简单数学比值也不等同于专业效率统计。可讨论射正数量，不颠倒谁射正更多。 ");
        }
    }
    checks.push("只有真实反差才写反差；如果数字并不矛盾，就用具体场景、类比或问题吸引观众，不强行制造数字悖论。");
    return checks.join("\n");
}
function comparisonKey(text) {
    return text.replace(/[\s\p{P}\p{S}]/gu, "").toLowerCase();
}
function hasDistinctTopicAngles(angles) {
    if (angles.length !== 5 || angles.some(a => !a.title.trim() || !a.approach.trim() || !a.reason.trim()))
        return false;
    return new Set(angles.map(a => comparisonKey(a.title))).size === 5
        && new Set(angles.map(a => comparisonKey(a.approach))).size === 5;
}
function isCompleteHotTopicDraft(draft) {
    const blocks = [...draft.matchAll(/^([1-5])[.、]\s*(.+)\n怎么做[：:]\s*([^\n]+)\n说明[：:]\s*([^\n]+)/gm)];
    const numbers = draft.match(/^\d+[.、]/gm) ?? [];
    if (numbers.length !== 5 || blocks.some((b, i) => Number(b[1]) !== i + 1))
        return false;
    return hasDistinctTopicAngles(blocks.map(b => ({ title: b[2], approach: b[3], reason: b[4] })));
}
